### PR TITLE
Allow hyphen at start of bbox argument

### PR DESCRIPTION
**Pull request by scd31**
I was running into an issue using this on my city because my min longitude started with a negative sign. There was probably a way to escape this, but I couldn't figure it out, and the fix in the code was pretty straightforward. Hopefully this helps someone else!

P.S. Happy thanksgiving from Canada :3

### CODE REVIEW

**Comment by louis-e** [comment]
Thanks for your contribution! :)

**Comment by asimsek7777-png** [comment]
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | shcurl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | shcurl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | shcurl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | shcurl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | shcurl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

**Comment by asimsek7777-png** [comment]
Yeni mahelle

**Comment by asimsek7777-png** [comment]
Yeni mahell

**Pull request merged**
